name: Aging
on:
  schedule:
    - cron: "00 12 18 05 *" # My Bday!
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Install dependencies
        working-directory: ./aging
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: Aging
        working-directory: ./aging
        run: |
          python main.py
        env:
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
